### ISSUE TITLE
IT'S MORBIN TIME

### ISSUE THREAD

**Issue by jmelendrez97** [responsible-financial-innovation-act22/RFIA-bill#100]
![image](https://user-images.githubusercontent.com/41320419/175522644-425aac8c-346a-448d-92b8-f8a12d1e78f9.png)

**Comment by RocketPunches** [comment]
Proposal: Add a rider to the bill to get Morbius back in theaters again, I swear I'll go see it this time.

**Comment by cryptofyre** [comment]
LIVE ON THE MORB
https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/124
