### ISSUE TITLE
I Bought Some Bitcoins, How Do I Get Them Into The Computer?

### ISSUE THREAD

**Issue by RocketPunches** [responsible-financial-innovation-act22/RFIA-bill#103]
I bought 5 Bitcoins from the kids down the street. They said it was a great deal because each of them was worth $20,000 and showed me on their phones how much they were worth, but they would sell them all to me for $2,000. I'm home now though and I can't get them into the computer. They don't fit in the big slot on the side that I put my DVDs in, but it's the only thing even close to large enough to take them.

**Comment by RocketPunches** [comment]
A chain? Is that something I can get at the hardware store?

**Comment by S0ulf3re** [comment]
Probably idk
