### ISSUE TITLE
Is Lummis even reading these issues?

### ISSUE THREAD

**Issue by woot000** [responsible-financial-innovation-act22/RFIA-bill#105]
Are you?

![IMG_20220617_230210124](https://user-images.githubusercontent.com/97068837/175531188-f2fb9c17-03f0-4bfd-860e-9613391d00e9.jpg)

**Comment by CrazedCoding** [comment]
They might need a pleb to reset their Twitter password, first...

**Comment by RocketPunches** [comment]
Nah. I'm sure the staffer that suggested it will check in at some point though. Hello staffer.
