### ISSUE TITLE
Most of the trolling here could be solved with one change: Temporary Interaction Limits

### ISSUE THREAD

**Issue by ademidun** [responsible-financial-innovation-act22/RFIA-bill#108]
Most of the posts here are people spamming and trolling.

However, there's an easy way to [fix this](https://github.com/atilatech/RFIA-bill/pull/4#issuecomment-1165531536). Set an [interaction limit](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository#about-temporary-interaction-limits).

> Limit to existing users: Limits activity for users with accounts that are less than 24 hours old who do not have prior contributions and are not collaborators.

My hypothesis is that many of the troll accounts were made in less than 24 hours so that small change would reduce the amount of trolling. 

**This won't stop all trolling but it will reduce the amount**

Not all troll accounts are less than 24 hours old. New accounts can wait for the timer to end and resume their trolling. This method is not perfect, but it's better.

We can adapt, iterate and add other such methods as we go. Once trolling become sufficiently difficult, eventually, the trolls will just give up and go be annoying somewhere else. Or they might even realize that they'd have more fun adding positive changes to the bill and being a part of history.

More importantly, it shows that we don't have to just give up and say "see, I told you this won't work". No. It can work. We just need to be proactive about coming up with good solutions.

However, I don't think this repo is actively managed so the trolling will most likely continue to proliferate here.

This is why I suggest that people who are serious about making positive contributions to this bill should contribute their ideas here instead: https://github.com/atilatech/RFIA-bill

**Comment by CrazedCoding** [comment]
If this repo was code instead propaganda maybe we'd get comments about how to improve it instead of meme pictures.
![download](https://user-images.githubusercontent.com/18431780/175539592-ff309031-6e74-4a96-a1b7-c84b108c9416.jpeg)

**Comment by frabaghe** [comment]
As much as that limiting interaction would reduce trolling, that would defeat the purpose of the inclusive and open access that the repo was meant to achieve.

**Comment by CrazedCoding** [comment]
> As much as that limiting interaction would reduce trolling, that would defeat the purpose of the inclusive and open access that the repo was meant to achieve. A non-user of GitHub who has genuine feedback should be allowed to sign up and comment. That's how open commenting systems work. (Sadly, it also invites fake bots).

Also: they need a way to post fake discussions about how their bill is buzzworthy... Apparently because GitHub is all about Nondeterministic laws, and blockchains require no coding experience to regulate.

Don't worry... Microsoft is on the case!

**Comment by RocketPunches** [comment]
Why do you want people to stop trolling this fundamentally unserious call for input on a bill that was blatantly bought and paid for by financial special interests? 

They don't care about this, it's just a PR ploy. They just want gullible retail crypto traders who have maybe run some code projects and view GitHub as a place for serious work to see them here and jump on board. All they care about is creating a spider web of tax dodges and regulation skirting for traditional finance. Well, that and passing the buck on dealing with the preponderance of scams in crypto spaces at the moment.

There's no reason for people who don't know what version control is, and whose idea of collaboration is someone writing them a check to distribute to their friends as campaign expenses during the next election, to be on GitHub at all. Congress people don't care about input from normal citizens or really about normal citizens at all. These are the same type of people that allow total trash like payday loans to devastate low income communities. They don't want to hear about the changes you make, they'll only read things their staffers cherry pick out of this thread.

This is marketing. Stop acting like a child.

**Comment by rickandm00rty** [comment]
> > I understand the skepticism behind this being posted on GitHub, but I am truly at a loss for the doomsday naysayer's. Maybe this is marketing. Maybe this is an ill-guided attempt to pander and market to a specific audience or avoid responsibility but isn't the idea and attempt at having a conversation at least worth taking seriously? I can't think of another single website that would allow revisions and commentary from technical folks who may have a background and knowledge in this space. Bots are one thing but trolling away the entire discussion just discourages any sort of conversation. Would you rather the video of this proposal be posted on Facebook or Reddit? Not sure what people think should happen in these areas but "stop acting like a child" and "they'll only read things staffers cherry pick" is just pure negativity. How about some suggestions instead of pure negativity???
> 
> How about a nice tall glass of pure code to actually make suggestions on? Not this "GIMME TAXES!!!" manifesto?

I don't expect anyone who works in a political field to be submitting code for potential bills that go into law for regulation. I don't know if that gap has ever been bridged before (hence the complexity of crypto regulation). So yes, we can just troll them away and say they are idiots with selfish interest but that certainly isn't going to bring any type of code-related revisions to the table. Can you suggest experts they can consult to produce such code? Other repo or discussion forums they should look at? Specific references to gaps in the proposed legislation or areas where power can be abused? Or are we simply just whining and saying this used to be a place for code?  How exactly do you expect "a tall glass of code" to go along with this? Typical whining without a single workable suggestion for people who are clearly out of their depth (any politician looking at this issue seriously) will only push them away and make them believe this technology is unworthy in our hands

**Comment by hallambaker** [comment]
Back in the earliest days of the Web, my colleagues at the MIT AI Lab ran a system called the Open Meeting which it ran for Al Gore and provided a discussion forum within the federal government on the proposed performance review changes.

That scheme succeeded because it was designed for the purpose.

Github is failing in exactly the ways I would expect it to fail for this application. Git is designed to support code development, not structured commentary on legislative proposals.

The proposal itself is an attempt at grandstanding. Politicians trying to jump on a technology bandwagon they can't be bothered to understand.

**Comment by rickandm00rty** [comment]
> Back in the earliest days of the Web, my colleagues at the MIT AI Lab ran a system called the Open Meeting which it ran for Al Gore and provided a discussion forum within the federal government on the proposed performance review changes.
> 
> That scheme succeeded because it was designed for the purpose.
> 
> Github is failing in exactly the ways I would expect it to fail for this application. Git is designed to support code development, not structured commentary on legislative proposals.
> 
> The proposal itself is an attempt at grandstanding. Politicians trying to jump on a technology bandwagon they can't be bothered to understand.

I  agree - Github does not serve as the best vector for this communication - where else would you suggest? These "tech" sectors and forums have so much gate keeping to them I don't expect a politician to understand them. Should this go on Reddit? Facebook?

**Comment by CrazedCoding** [comment]
> > > I understand the skepticism behind this being posted on GitHub, but I am truly at a loss for the doomsday naysayer's. Maybe this is marketing. Maybe this is an ill-guided attempt to pander and market to a specific audience or avoid responsibility but isn't the idea and attempt at having a conversation at least worth taking seriously? I can't think of another single website that would allow revisions and commentary from technical folks who may have a background and knowledge in this space. Bots are one thing but trolling away the entire discussion just discourages any sort of conversation. Would you rather the video of this proposal be posted on Facebook or Reddit? Not sure what people think should happen in these areas but "stop acting like a child" and "they'll only read things staffers cherry pick" is just pure negativity. How about some suggestions instead of pure negativity???
> > 
> > 
> > How about a nice tall glass of pure code to actually make suggestions on? Not this "GIMME TAXES!!!" manifesto?
> 
> I don't expect anyone who works in a political field to be submitting code for potential bills that go into law for regulation. I don't know if that gap has ever been bridged before (hence the complexity of crypto regulation). So yes, we can just troll them away and say they are idiots with selfish interest but that certainly isn't going to bring any type of code-related revisions to the table. Can you suggest experts they can consult to produce such code? Other repo or discussion forums they should look at? Specific references to gaps in the proposed legislation or areas where power can be abused? Or are we simply just whining and saying this used to be a place for code? How exactly do you expect "a tall glass of code" to go along with this? Typical whining without a single workable suggestion for people who are clearly out of their depth (any politician looking at this issue seriously) will only push them away and make them believe this technology is unworthy in our hands

There is already an open issue regarding the feebleness plebs: https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/107#issue-1283692732

All hail our great overlord oligarchy government! May they always deem us filthy scum worthy of doing math!

**Comment by CrazedCoding** [comment]
> 

I disagree. The aristocratic hubris sociopathic non-technical politicians and religious leaders are too full of themselves to ever want to learn objective balanced mathematics and programming, and certainly can't allow it lest they lose their reproductive edge.

Human DNA is actually a set of binary codes, too. Too bad we have to keep giving your political faith based subsets the benefits of doubt. Maybe us plebs would be "worthy" of technology then?

**Comment by CrazedCoding** [comment]
> I'll keep my response short, just for you; Do you believe you can do the job of a politician and do the programming? There is a reason these fields are so separated. Your comments are the equivalent of saying "git gud" to politicians. What exactly have you provided to this conversation that is "well though out"?

How succinct. Nice job 👍

The fields aren't separated. Like every other field, it just takes a long time, in this case decades, to catch up with computer science. So: yes, I could, but people would actually have to want a one-identity-one-vote democracy. But: politicians spent all USA money on military, not altruistic technologies, and needs ww3 to happen soon so it doesn't lose dominance over superior technological economies.

I don't know? You tell me. A third perspective that doesn't target a particular user, but the issues at hand.

Thank you for shortening your responses.

**Comment by rickandm00rty** [comment]
Do you have any hope that regulation on blockchain technologies can be solved in a political sphere w/ technical input? I suspect this is where we differ fundamentally. I believe it can but any well-meaning politician will be shied away from engaging on these platforms if we troll them by asking for things they cannot provide (decades of CS experience)

**Comment by responsible-financial-innovation-act22** [comment]
> Most of the posts here are people spamming and trolling.
> 
> However, there's an easy way to [fix this](https://github.com/atilatech/RFIA-bill/pull/4#issuecomment-1165531536). Set an [interaction limit](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository#about-temporary-interaction-limits).
> 
> > Limit to existing users: Limits activity for users with accounts that are less than 24 hours old who do not have prior contributions and are not collaborators.
> 
> My hypothesis is that many of the troll accounts were made in less than 24 hours so that small change would reduce the amount of trolling.
> 
> **This won't stop all trolling but it will reduce the amount**
> 
> Not all troll accounts are less than 24 hours old. New accounts can wait for the timer to end and resume their trolling. This method is not perfect, but it's better.
> 
> We can adapt, iterate and add other such methods as we go. Once trolling become sufficiently difficult, eventually, the trolls will just give up and go be annoying somewhere else. Or they might even realize that they'd have more fun adding positive changes to the bill and being a part of history.
> 
> More importantly, it shows that we don't have to just give up and say "see, I told you this won't work". No. It can work. We just need to be proactive about coming up with good solutions.
> 
> However, I don't think this repo is actively managed so the trolling will most likely continue to proliferate here.
> 
> This is why I suggest that people who are serious about making positive contributions to this bill should contribute their ideas here instead: https://github.com/atilatech/RFIA-bill

Done. Thank you!

**Comment by CrazedCoding** [comment]
> Do you have any hope that regulation on blockchain technologies can be solved in a political sphere w/ technical input? I suspect this is where we differ fundamentally. I believe it can but any well-meaning politician will be shied away from engaging on these platforms if we troll them by asking for things they cannot provide (decades of CS experience)

No. I have hope government and faith based politics can be regulated by an open and free capitalist market based on Blockchain, and supply/demand.

For pack of a better analogy: I don't try to drill holes into wood by hammering drill with a nail.

**Comment by CrazedCoding** [comment]
> I believe you have far too much hope in the average person but maybe that's a positive thing. Many people will be abused by a free and open market without some sort of regulation on Blockchain rules. I believe its unrealistic for people to understand this innovation and all of its implications. Regardless - I'll stop wasting your time. Thanks for engaging in this discussion even if it was frustrating for you

No problem. It was certainly hilarious.

**Comment by coolswag88** [comment]
no
