### ISSUE TITLE
Nice.

### ISSUE THREAD

**Issue by that-guy-is-it** [responsible-financial-innovation-act22/RFIA-bill#114]
Status before this Issue Opens:

<img width="121" alt="Nice" src="https://user-images.githubusercontent.com/25746744/175570086-70f83aef-3bfa-4835-b87f-bce5e943a3ca.png">

Nice.

![USA FREEDOM](https://user-images.githubusercontent.com/25746744/175570244-28651b61-40a1-45ab-9d22-3cc6737f61b7.jpeg)

Further, let's make it mandatory under penalty of law to 360 no scope all scrubs, fite me irl

**Comment by that-guy-is-it** [comment]
<img width="114" alt="Nicer" src="https://user-images.githubusercontent.com/25746744/175570773-f93698da-dfbb-4b66-9017-6a3315f5094d.png">

Nice.

**Comment by twl-surrogate** [comment]
yall really think this is funny 💀💀

**Comment by ioletsgo** [comment]
Nice.

**Comment by notnullnotvoid** [comment]
> yall really think this is funny 💀💀

Yes.
