### ISSUE TITLE
I'm just a Bill

### ISSUE THREAD

**Issue by Tamim-Nekaien** [responsible-financial-innovation-act22/RFIA-bill#117]
Yes, I'm only a bill.
And I'm sitting here on Internet Hell.
Well, it's a long, long journey
To the capital club.
It's a long, long wait
While I'm sitting in Github,
But I know I'll be a law some day
At least I hope and pray that I will
But today I am still just a bill.

**Comment by jonmarrs** [comment]
[I'm Just a Bill](https://youtu.be/OgVKvqTItto)

**Comment by bnlcas** [comment]
Well there are a lot of flag There's a lot of flag burners
Who have got too much freedom,
I wanna make it legal
For policemen to beat 'em.
'Cos there's limits to our liberties,
Least I hope and pray that there are,
'Cos those liberal freaks go too far.
..
Then I'll crush all opposition to me
And I'll make Ted Kennedy pay
If he fights back
I'll say that he's gay
..
