### ISSUE TITLE
do you guys like my fursona

### ISSUE THREAD

**Issue by owocean** [responsible-financial-innovation-act22/RFIA-bill#118]
# he's a bat his name is iris  

![image](https://user-images.githubusercontent.com/43656163/175618955-945f84e4-35d9-47e1-9686-e25c0c1419f6.png)
![image](https://user-images.githubusercontent.com/43656163/175618996-e78d7686-7e17-4d42-a0ed-77c7780c13ba.png)

**Comment by ithotu** [comment]
good fursona op

**Comment by Firenocki** [comment]
No actually



I love your fursona

**Comment by gltile-two-electric-boogaloo** [comment]
i love him 🥺

**Comment by VRBat** [comment]
I LOVE HIM SO MUCH

**Comment by owocean** [comment]
@VRBat ![image](https://user-images.githubusercontent.com/43656163/175754129-19da4046-8e59-4224-ba55-40b7a03b6402.png)

**Comment by Codfish246** [comment]
awesome

**Comment by coolswag88** [comment]
cool fursona

**Comment by kiosion** [comment]
yes
