### ISSUE TITLE
Proposal: Separate repository to discus the meta issue of using GitHub

### ISSUE THREAD

**Issue by hallambaker** [responsible-financial-innovation-act22/RFIA-bill#119]
Some history, back in 1992 I saw a presentation on a small hypertext project with roughly 100 users at the Annecy CHEP conference. I was so impressed that I emailed my friend Jock Gill who was running the Clinton-Gore '92 online to tell him that he should look at it because it was going to be the future of politics and campaigning. That project was the World Wide Web.

This github is an attempt to achieve something we called then 'mass listening'. And it is a really hard problem. I later joined a team that put the Web into the Whitehouse, was directly involved with creation of whitehouse.gov and set up the publications service which sent out all Clinton's presidential press releases. One to many communication, that is broadcast communication is easy. Many to one or many to few is desperately hard.

There are tools designed to do this. Github is not one of those tools. GitHub is owed by Microsoft however which has a large public affairs office and a research division interested in issues of this type.

Rather than proposing to use a particular tool, I think it would be better to open a discussion about what the capabilities and affordances of such a system should be. There are mechanisms that can be used to guide and curate conversations so they are not dominated by irrelevance and trolls.

Finally, 'Crypto-currencies' are not a technology issue, it is a financial issue. Casting the issue as primarily technical and directing the discussion to a technology oriented site invites comment from people whose primary expertise is in technology, most of whom have minimal interest in understanding how financial markets actually operate in practice.

**Comment by CrazedCoding** [comment]
This issue has been closed by the maintainers of this repo already: https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/106#issuecomment-1165541657

**Comment by steakknife** [comment]
> This issue has been closed by the maintainers of this repo already: https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/106#issuecomment-1165541657

Was it fixed in this release or forked into 3 other projects without a clear winner?

**Comment by CrazedCoding** [comment]
> > This issue has been closed by the maintainers of this repo already: [#106 (comment)](https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/106#issuecomment-1165541657)
> 
> Was it fixed in this release or forked into 3 other projects without a clear winner?

If by solved you mean ignored/dismissed and forgotten, then, yes. Law and politics seem to do this so they can exist forever in their primordial technological forms.

No, thank you. Pass a spoon, instead, please.

**Comment by kentkos** [comment]
I'm going to go out on a limb and say Microsoft and GitHub approved the bill being posted as a repo.
