### ISSUE TITLE
How about a TLDR?

### ISSUE THREAD

**Issue by Hueristic** [responsible-financial-innovation-act22/RFIA-bill#120]
I'll read this monstrosity when senators actually read the bills they vote on.

**Comment by steakknife** [comment]
> I'll read this monstrosity when senators actually read the bills they vote on.

To be fair, that's a threat against your own interests to give policymakers a license to mostly the rich to enact laws they want so long as they're sufficiently obsfucated from your comprehension and/or patience.

**Comment by CrazedCoding** [comment]
> > I'll read this monstrosity when senators actually read the bills they vote on.
> 
> To be fair, that's a threat against your own interests to give policymakers a license to mostly the rich to enact laws they want so long as they're sufficiently obsfucated from your comprehension and/or patience.

Ya! We're on a HOLY mission to defeat math! Waste your time on learning our unevolvable propaganda, or else the satanist programmers win!!

Trump 2024!

**Comment by takipsizad** [comment]
simply we fuckers have tax on crypto currency
