### ISSUE TITLE
nine circle

### ISSUE THREAD

**Issue by SuperSpaceMan230** [responsible-financial-innovation-act22/RFIA-bill#121]
nin circel 

https://user-images.githubusercontent.com/61877191/175699088-d6bd048e-3d68-43f7-acb2-31a2c4811fef.mp4

**Comment by SuperSpaceMan230** [comment]
![SoyMilkIsaac](https://user-images.githubusercontent.com/61877191/175699239-4bf91999-f785-427e-89fb-9e6e4e8acd20.png)
look at this isac too

**Comment by Maximal98** [comment]
good perf bro
