### ISSUE TITLE
my progress on clubstep

### ISSUE THREAD

**Issue by SuperSpaceMan230** [responsible-financial-innovation-act22/RFIA-bill#123]
![image](https://user-images.githubusercontent.com/61877191/175699679-9380efb0-326f-4833-bb9f-7a10a25634bc.png)
clubstep

**Comment by SuperSpaceMan230** [comment]
0-29%
![image](https://user-images.githubusercontent.com/61877191/175699753-728889df-e484-459f-9a4b-cff8fd34d6fb.png)

**Comment by SuperSpaceMan230** [comment]
0-33%
![image](https://user-images.githubusercontent.com/61877191/175699929-f3b85ad8-ca29-4d16-a5c1-d39a42a9b20c.png)

**Comment by coolswag88** [comment]
whats your progress rn
