### ISSUE TITLE
PSA: Bitcoin is frying your brain

### ISSUE THREAD

**Issue by SuperSpaceMan230** [responsible-financial-innovation-act22/RFIA-bill#125]
### ALERT!!!

Hello, this is not a troll post, this is a serious post, backed by millions of health tests and health exams after one bitcoin.

I'm dr M1nx, don't question my name, but trust me when i tell you that bitcoin transactions are quite literally deteriorating your brain, mint by mint

### Bitcoin is frying your brain, but how?

Bitcoin takes lot of energy to transfer, and all that energy is going near your head, that's where the frying pa rt comes in, the data load is so massive that it going near your brain is slowly deteriorating it, it's literally cooking your brain!

Here's a diagram about how it works
![image](https://user-images.githubusercontent.com/61877191/175720212-bee35d6c-8dae-43a0-a9d6-39dd5b9d5b82.png)

### How can i trade my bitter whilst staying safe?

The way to keep yourself safe is thankfully safe and affordable, here's how

1. Buy Aluminum foil, make sure it's strong enough
2. Wrap it around your head to make your bitcoin-safe headband, make sure you shape it in such a way that it will stay still, so you can wear it whenever you want
3. **IMPORTANT STEP!** Take out your headband, and put it inside any microwave, you can squish it if you want but make sure you put it back in shape, **Microwaving the foil will radiate it, which will completely negate bitcoin radiation due to how powerful the radiation is, although it's not harmful to humans**
4. Put the headband on whenever you need to do a bitcoin transaction

### Conclusion

Please make sure you follow these steps while transacting bitcoin, because not doing so is risking your life just for 
###  MONEY!

Thank you

-Dr M1nx

**Comment by SuperSpaceMan230** [comment]
please spread awareness everyone must know the harm of bitcoin

**Comment by Vukkyy** [comment]
"no way! no way! is it a hypnospace reference? please tell me it's a hypnosp
> M1nx

**Comment by joelsgp** [comment]
Right honourable Sen. Lumens, what action have you taken to address this important issue, having closed it?
