### ISSUE TITLE
seal

### ISSUE THREAD

**Issue by wukko** [responsible-financial-innovation-act22/RFIA-bill#136]
![20220619_125826](https://user-images.githubusercontent.com/71202418/175755849-d97696f5-ef98-4d1b-9445-bf3380ad6c9a.jpg)

**Comment by Codfish246** [comment]
awesome seal
🚀

**Comment by ijre** [comment]
Please make into PR and insta merge, seal adds necessary componants of any good repo thanks
![weddell-seal-whiskers 1200x630](https://user-images.githubusercontent.com/33820042/175758313-1ce1e931-c89a-4487-8da9-566332583faf.jpg)

**Comment by kiosion** [comment]
this is important! 🦭

**Comment by Codfish246** [comment]
seal completed
