### ISSUE TITLE
Coding Challenge for the Community!

### ISSUE THREAD

**Issue by CrazedCoding** [responsible-financial-innovation-act22/RFIA-bill#140]
Write a cryptocurrency repo in fewer characters than this bill.

We could then try to pass that repo as a bill.

It'd be fun to watch all the senators try to catch up on actually useful technical knowledge, and fall flat on their fat faces.

**Comment by swift502** [comment]
It's been done, a minimal crypto coin implementation can have only a couple hundred lines of code. https://github.com/akbng/crypto-coin

And all it proves is that crypto is very primitive, and legal language very complicated.

**Comment by CrazedCoding** [comment]
I disagree. It proves 5 minutes of coding produces something 1000x more useful than any amount of legal studies.

Additionally, it seems to indicate that language doesn't have to be limited to objectiveless, greedy, math-anxiety-striken senators who never grew up because their parents had too much money, power, and/or influence.

Basically you just linked a modern weapon of mathematics that they are trying to fight with legal jargon, political favors, and subjective "creative" writing.

The fact that it occupies less space than the bill just go to show how much senators like these are wasting everyone's time, space, and energy just by simply existing.

What if all the worlds programmers suddenly got as greedy as this senator and simply poured all their time space and energy into working on viruses, scams, and closed source projects? I think it would actually be a balancing method of preventing legal scammers, like senators, from constantly wrecking freedoms that were actually well thought out to begin with.

**Comment by DannyLeWasTaken** [comment]
nah

**Comment by CrazedCoding** [comment]
> nah

Holy cow.

Absolutely brilliant. I never would have thought of this!

**Comment by CrazedCoding** [comment]
> It's been done, a minimal crypto coin implementation can have only a couple hundred lines of code. https://github.com/akbng/crypto-coin
> 
> But all it shows is that the blockchain is a relatively primitive technology, and legal language is very complicated.

Someone changed my opinion: we should continue letting political and religious leaders be evil by lying about their moral superiority to tell everyone what to do, then: either (A) there are really eternal consequences for being evil supremacists, or (B) there isn't a God, and their ever growing numbers of unaborted well-fed offspring will perpetually have to live in increasing amounts of desperation of actually objective and good truths (until man-kind fully devolves back into something *really* "primitive").
