### ISSUE TITLE
Add clarification that "uncivil" contributions are welcome - and legally protected

### ISSUE THREAD

**Issue by BillyWM** [responsible-financial-innovation-act22/RFIA-bill#148]
You said on Twitter that "[civil comments and criticisms are welcome](https://twitter.com/CynthiaMLummis/status/1539714068872699904)"

By conducting official government business through this Github repository, it is automatically transformed into a **"public forum"**\* and afforded the very, very strong speech protections that entails. 

Contributors are not required to be "civil" here. They have the full First Amendment right to be free from "content-based" discrimination against their speech. Censoring their speech due to the manner of expression or offense it causes, especially in a virtual forum where it cannot lead "an ordinary person.... to imminent lawless action", is almost certain to be a violation of their constitutional rights

 (As a good Republican, don't you support the First Amendment? Or do you hate America?)

**If you are a contributor whose account is blocked by this senator or your comments are deleted, please reach out to the local chapter of the ACLU and sue her**. 

Even a 6-3 MAGA-SCOTUS will uphold 1A. I *dare* you to give us the standing, senator!

\* possibly a "designated forum", but no matter as this has the same protections as a "traditional public forum"

**Comment by NathanPeake** [comment]
Your "Amendment"'s don't translate to any online space.

**Comment by BillyWM** [comment]
[Additional information](https://knightcolumbia.org/content/second-circuit-denies-full-court-review-of-decision-holding-that-president-trump-violated-first-amendment-by-blocking-critics-on-twitter)

> “The First Amendment bars the president from blocking users from his account simply because he dislikes or disagrees with their tweets,” said Katie Fallow, Senior Staff Attorney at the Knight Institute. “This case should send a clear message to other public officials tempted to block critics from social media accounts used for official purposes.”

> The Second Circuit was the second appellate court in the country to hold that a public official’s social media account can sometimes be a public forum under the First Amendment. In January of last year, in a case also argued by the Knight Institute, the U.S. Court of Appeals for the Fourth Circuit found in favor of Brian Davison, a Virginia resident who was temporarily blocked from the Facebook page of a local public official.

**Comment by BillyWM** [comment]
And furthermore....

> The US Court of Appeals for the Fourth Circuit affirmed the decision of the District Court finding that Loudoun County School Board (LCSB) Chair Phyllis Randall’s Facebook page constituted a public forum and that she did not maintain it in a lawful manner. **Randall had deleted comments posted by Davison on her Chair’s Facebook page that included allegations of corruption and conflicts of interest within the LCSB and she subsequently banned him** for 12 hours from the Facebook page. The Court found that by engaging in viewpoint discrimination on her Facebook page, the Chair violated the Plaintiff’s freedom of speech rights under the First Amendment and was not entitled to block the Plaintiff or any citizens from commenting on her Facebook page.

(emphasis mine)

I see similar accusations of corruption being made here. **The senator(s) are similarly prohibited from banning you for those claims here** especially as they are *directly relevant* to the legislation at hand. If this happens to anyone who may read this, **please**, do contact your local chapter of the ACLU

https://www.aclu.org/about/affiliates

Precedent-setting decisions are good for all of us but you could also get a fat paycheck in a settlement!
