### ISSUE TITLE
Can you explain this image?

### ISSUE THREAD

**Issue by woot000** [responsible-financial-innovation-act22/RFIA-bill#24]
What does it mean?

![FTFx6M5UsAEj1me](https://user-images.githubusercontent.com/97068837/175400230-dbf1ee5c-4430-4f5c-9517-92c9872524cb.jpg)

**Comment by RocketPunches** [comment]
Can we get a comment from an expert? I'm sure there's gotta be an expert in this on a site like GitHub.

**Comment by woot000** [comment]
Also of interest: [Wario64 just tweeted](https://twitter.com/Wario64/status/1540081546534670338) about how Chris Pratt's voice for Mario in the upcoming Mario movie made by Illumination and describes it as "unlike anything you've heard in the Mario world before".

I think that's rather intriguing. What about you?

**Comment by morellam-dev** [comment]
From https://en.wikipedia.org/wiki/Super_Mario_3D_World,
> ***Super Mario 3D World*** is a platform game developed and published by Nintendo for the Wii U in 2013. It is the sixth original 3D platform game in the *Super Mario* series and the sequel to *Super Mario 3D Land* (2011) for the Nintendo 3DS.

**Comment by TheEssem** [comment]
I heard a rumor that Super Mario Bros. 2 is not actually a Mario game, but is instead a reskin of a Japanese game called Doki Doki Panic. I personally don't believe this one, what do you guys think?

**Comment by RocketPunches** [comment]
> 

Sounds like someone's uncle "works at Nintendo" to me

**Comment by FourteenCoast** [comment]
It's just not normal

**Comment by thomascampbelladams** [comment]
We need all hands on deck for this problem.

**Comment by NyakoFox** [comment]
I'm unsure if "Mario" is actually real so this should be closed as invalid

**Comment by RocketPunches** [comment]
Idk, Mario seems like a pretty reproducible phenomenon. I mean, I've seen him show up in like 200 games at this point so I'm starting to think this is just a problem with some old code Nintendo is providing to people who work with them.

**Comment by TheEssem** [comment]
Once again, the US government is trying to cover up the existence of Mario. Typical.

**Comment by SuperSpaceMan230** [comment]
they are censoring us

**Comment by Codfish246** [comment]
watch out before they mark this as invalid and lock to collaborators! many such cases

**Comment by NyakoFox** [comment]
I take it back guys, Mario is definitely real and I'm so sorry about my prior viewpoint. The censorship they're using against him is insane and I wish everyone involved the best. Mario doesn't deserve this.
