### ISSUE TITLE
This is the best issues section I've ever seen on GitHub 

### ISSUE THREAD

**Issue by S0ulf3re** [responsible-financial-innovation-act22/RFIA-bill#28]
In the past decade I've used GitHub (I made my account in 2019 but lurked here for ages), This is hands down the best issues section ive seen

**Comment by S0ulf3re** [comment]
Also who's here from https://web3isgoinggreat.com ?

**Comment by zipplet** [comment]
This is honestly pure work here. All of is are doing our best for the common good.

**Comment by technoY2K** [comment]
> In the past decade I've used GitHub (I made my account in 2019 but lurked here for ages), This is hands down the best issues section ive seen

I was thinking the exact same thing.

**Comment by S0ulf3re** [comment]
@responsible-financial-innovation-act22 Y'all are boring
