### ISSUE TITLE
This bill is missing a provision to jail all crypto businesspeople, scammers, and cult leaders

### ISSUE THREAD

**Issue by Adil3tr** [responsible-financial-innovation-act22/RFIA-bill#30]
Crypto has no serious uses whatsoever, that's objectively the case. Instead it's simply a way for the perverse or highly technical to parasitically extract value from actual human beings. What this bill is missing is not just banning crypto currency and incentive based block chains, but also a way to eradicate the entire phenomenon from society. 

I propose we could do this quickly and efficiently by jailing all leading crypto-bros, and making any unique or exclusionary blockchain based assets not just illegal but legally forfeited in both asset and intellectual property. Side measures could be making it legal for crypto-people to violate contracts with each other, steal from each other, and generally not benefit from social authority or the court system, until the entire structure collapses in a cyclone of scams.

Progress is hard but we need to be bold and not shy away from basic realities about the future of finance. Namely how much better it'll be with all big name crypto people, whom we would refer to by the acronym TAPEWORMS, sitting in a prison while people sentenced for low level drug offenses are set free. The US military and state department interfering in foreign nation's affairs to protect the value of the US dollar internationally is truly a bad thing, but sending them to the next crypto conference to collect all of the speakers and crypto start up leaders, that would be quite good.

I have no interest in my future being lived within a cage built by the most poorly socialized shut-ins in history, and neither does any American. I demand these common sense measures that every American can get behind from my legislators.

**Comment by RocketPunches** [comment]
I wonder if a digital ledger would be useful in tracking down people who value digital ledgers too much.
