### ISSUE TITLE
Crypto Is Essential for US Technology Leadership and Innovation

### ISSUE THREAD

**Issue by OyeOye-12** [responsible-financial-innovation-act22/RFIA-bill#31]
Crypto, Bitcoin and Blockchain are essential for the US to maintain its position as a leader in technology and innovation (we are currently being passed by many other countries and regions).  It is absolutely time we pass this important legislation and get it right!  So that US blockchain and technology companies can have regulatory clarity and innovate, and so that financial companies can participate in a constructive way in this space.  Glad to see this effort, and looking forward to some timely and essential legislation and regulation for the crypto, FinTech, and blockchain space in the US.

**Comment by joelself** [comment]
Crypto companies are already very innovative in the way they fleece their customers.
