### ISSUE TITLE
What happened to your BTC Sent Lummis?

### ISSUE THREAD

**Issue by karan** [responsible-financial-innovation-act22/RFIA-bill#37]
https://www.cnbc.com/2021/10/07/senator-cynthia-lummis-discloses-a-bitcoin-purchase-worth-up-to-100000.html

https://www.protocol.com/fintech/lummis-crypto-interview

"You know, I got so much grief for owning bitcoin that I put everything in a blind trust."

"I'm holding on to my bitcoin for as long as I can and I hope to be able to pass them to my grandsons because I just believe they're going to, in the long run, hold value and grow in value and I'm looking for a store of value. That is the reason I personally hold bitcoin."

So are they in a blind trust, or do you personally hold them?

Both can't be true at the same time.

**Comment by ashleydavies** [comment]
Gotta love people with publicly declared vested interests writing favourable financial legislation!

**Comment by karan** [comment]
Cowards.
