### ISSUE TITLE
all my apes gone

### ISSUE THREAD

**Issue by maymike321** [responsible-financial-innovation-act22/RFIA-bill#44]

**Comment by ashleydavies** [comment]
This is a real shame, because if you still had your apes you could use multiple slurp juice on a single ape

**Comment by thomascampbelladams** [comment]
ODO ALL MY APES ARE STOLEN

**Comment by caelx** [comment]
Found em

**Comment by maymike321** [comment]
this issue was closed as completed but my apes are still gone
