### ISSUE TITLE
All my doom wads gone

### ISSUE THREAD

**Issue by zipplet** [responsible-financial-innovation-act22/RFIA-bill#45]
There is a PR here to fix this, it needs urgently merging. It would greatly enhance the project.

Steps:

- [ ] Merge in doom wads in PR #29 
- [ ] Make second PR to merge Zandronum source for multiplayer
- [ ] Bring someone in to the team to make a deathmatch WAD we can use for discussion of the bill

Can a bill run doom? Soon it will be able to.

**Comment by coolswag88** [comment]
the future is soon old men. if you can't win a match of doom multiplayer, you shouldn't be able to make laws. simple as that.

**Comment by coolswag88** [comment]
this is not completed, @responsible-financial-innovation-act22. reopen this issue.
