### ISSUE TITLE
Bat thread

### ISSUE THREAD

**Issue by VRBat** [responsible-financial-innovation-act22/RFIA-bill#50]
why waste our time on pretend money when we could focus on saving endangered species, like bats! and at some point, ourselves!

![image](https://user-images.githubusercontent.com/74703199/175439476-4f024d39-2ebf-4c77-9e4f-1d7aeb06d4e6.png)

**Comment by fennewald** [comment]
![image](https://user-images.githubusercontent.com/23765149/175440756-985f9f20-0270-4330-b8db-d5c20358ead9.jpeg)

**Comment by sneakers-the-rat** [comment]
![94d37b7dc96e43f2264c207bfe3b1188](https://user-images.githubusercontent.com/12961499/175459789-b95c062a-aa49-445c-8e30-97004d46ae4b.jpg)
did you know some bats have such good echolocation that they can sense the texture on the wings of a moth and distinguish between tastier and less tasty species?

**Comment by ThatOneCalculator** [comment]
Fruit bats are my favorite! How 'bout y'all?

![image](https://user-images.githubusercontent.com/44733677/175461869-1fe522af-3c07-4515-b113-ecfeb2d4b8dd.png)
![image](https://user-images.githubusercontent.com/44733677/175461871-e7c0f615-3a55-4a99-85a1-bf1a0f7db436.png)
![image](https://user-images.githubusercontent.com/44733677/175461882-a59af907-db11-480c-a753-1f030880384e.png)
![image](https://user-images.githubusercontent.com/44733677/175461886-5ed59db8-0557-43f0-9154-c7b1c6ca711e.png)
![image](https://user-images.githubusercontent.com/44733677/175461890-064b1aaa-1ec7-407b-a70a-754e33a345ed.png)

**Comment by Zyro1331** [comment]
![image](https://user-images.githubusercontent.com/49619936/175521777-5edb9813-f7c0-492b-a926-71f0ab50d77e.png)
![image](https://user-images.githubusercontent.com/49619936/175521888-4069fc69-0109-44b8-849d-a1bdf44cc4eb.png)
bats are cool 👍🏻
