### ISSUE TITLE
Do you think an Ambient Music GF is a plausible reality?

### ISSUE THREAD

**Issue by BJSwan** [responsible-financial-innovation-act22/RFIA-bill#58]
Hear me out, I think there are definitely some ambient artists that are accessible enough to make discovering an ambient gf a relatively easy possibility; perhaps if you walk into a local book store or even a large Barnes & Noble, a girl will have even an ambient interlude from Burial's Untrue streaming into her ears?

Then perhaps during sunrise on your beach holiday in Bulgaria... she pulls out her Zune from her back pocket and you both share a moment listening to Music for Airports... she grabs your hand and tells you she loves you when another layer of drone bursts through your eardrums... Delight, simply delight.

My question to you is - and I must put it bluntly - is an Ambient GF (or BF for some folk) plausible in our trying times?

Perhaps with the recent trend of Spotify and Apple Music's studying playlists/algorithms which definitely promote a lot of easy-listening drone ambient to a keen new wave of mindful students. As more people are exposed to ambient in the mainstream, will a qt 3.14 cutiepie gf whisper in your ear at the library, "Bloody hell, wack some Eno on before I lose my fucking marbles!" A man can dream.

I sure hope I can find an ambient music gf someday, and maybe you guys could share some stories of ambient music gf love and lust as well - maybe you even have an ambient music gf? Godspeed, and god bless.

**Comment by MatthewNavy** [comment]
Marked as closed immediately, chad move
