### ISSUE TITLE
I would never have expected the government to support pyramid schemes, but alas, here we are

### ISSUE THREAD

**Issue by drxt** [responsible-financial-innovation-act22/RFIA-bill#95]
This is a fast path to the cultural regression and becoming a hillbilly backwater where the powerful use the state apparatus to swindle and grift the people with impunity. The fact that a Democrat is one of the main co-sponsors of this bill proves how detached from reality they are from the needs of the people they represent, and how ultimately it's money that talks, money they actively extract from the shrinking middle class. 

As crypto bros are accustomed to saying: "Enjoy being poor"

**Comment by NathanPeake** [comment]
Related #9
